# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-kilted-livox-ros-driver2
  version: 1.2.4
source:
  git: https://github.com/Livox-SDK/livox_ros_driver2.git
  tag: 1.2.4
  target_directory: ros-kilted-livox-ros-driver2/src/work
  patches:
    - patch/ros-kilted-livox-ros-driver2.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 10
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform == 'emscripten-wasm32'
      then:
        - ros-kilted-rosidl-default-generators
    - if: build_platform != target_platform
      then:
        - git
  host:
    - apr
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libboost-devel
    - livox-sdk2
    - numpy
    - pcl
    - pip
    - python
    - ros-kilted-ament-cmake-auto
    - ros-kilted-ament-lint-auto
    - ros-kilted-ament-lint-common
    - ros-kilted-pcl-conversions
    - ros-kilted-rcl-interfaces
    - ros-kilted-rclcpp
    - ros-kilted-rclcpp-components
    - ros-kilted-rcutils
    - ros-kilted-ros-environment
    - ros-kilted-ros-workspace
    - ros-kilted-rosidl-default-generators
    - ros-kilted-sensor-msgs
    - ros-kilted-std-msgs
    - ros2-distro-mutex 0.10.* kilted_*
    - vtk-base
    - if: build_platform == target_platform
      then:
        - git
    - if: linux
      then:
        - libgl-devel
        - libopengl-devel
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
  run:
    - apr
    - git
    - libboost-devel
    - pcl
    - python
    - ros-kilted-pcl-conversions
    - ros-kilted-rcl-interfaces
    - ros-kilted-rclcpp
    - ros-kilted-rclcpp-components
    - ros-kilted-rcutils
    - ros-kilted-ros-workspace
    - ros-kilted-rosbag2
    - ros-kilted-rosidl-default-runtime
    - ros-kilted-sensor-msgs
    - ros-kilted-std-msgs
    - ros2-distro-mutex 0.10.* kilted_*
    - vtk-base
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
